Importing libraries

In [ ]:
#Importing the kibraries to be used
import pandas as pd

import numpy as np

Loading dataset

In [ ]:
#importing libraries 
import pandas as pd

import numpy as np

Loading datasets

In [ ]:
#Loading the autolib dataset to be used in this analysis
df=pd.read_csv('Autolib_dataset (2).csv')

Previewing dataset

In [ ]:
df.head(10)

                              Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23
5                8 Boulevard Voltaire     0                0  ...    6     7       2
6                      37 rue Leblanc     0                0  ...    8    18      20
7         17 Rue des Luaps ProlongÃ©e     3                3  ...    4    22      13
8               34 avenue Jean Moulin     1                1  ...    2    22      58
9        41 boulevard de Rochechouart     6                6  ...    4    15       2

[10 rows x 25 columns]

In [ ]:
#Accessing information about the data set
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar counter      5000 non-null   int64
 3   Utilib counter       5000 non-null   int64
 4   Utilib 1.4 counter   5000 non-null   int64
 5   Charge Slots         5000 non-null   int64
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots                5000 non-null   int64
 17  Station type         5000 non-null   object
 18  Status               5000 non-null   object
 19  Subscription status  5000 non-null   object
 20  year                 5000 non-null   int64
 21  month                5000 non-null   int64
 22  day                  5000 non-null   int64
 23  hour                 5000 non-null   int64
 24  minute               5000 non-null   int64
dtypes: int64(12), object(13)
memory usage: 976.7+ KB

Data Cleaning

Validity

In [ ]:
# Procedure 1: Irrelevant Data Observation
# Data Cleaning Action: Dropping geo point , displayed comment , and scheduled at attributes
# Explanation:No question to be answered requires this columns.
#
df.drop(["Geo point" , "Displayed comment" ,"Scheduled at"], axis = 1, inplace = True)
df.head(10)

                              Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23
5                8 Boulevard Voltaire     0                0  ...    6     7       2
6                      37 rue Leblanc     0                0  ...    8    18      20
7         17 Rue des Luaps ProlongÃ©e     3                3  ...    4    22      13
8               34 avenue Jean Moulin     1                1  ...    2    22      58
9        41 boulevard de Rochechouart     6                6  ...    4    15       2

[10 rows x 22 columns]

In [14]:
#Procedure 2 : Syntax Errors -  Checking for syntax errors of leading or tailing white spaces in the dataset

df['Address'] = df['Address'].str.strip()
df['Address']
df['ID'] = df['ID'].str.strip()
df['ID']

0                         paris-suffren-2
1              paris-raymondlosserand-145
2       lebourget-johnfitzgeraldkennedy-2
3                   paris-eugeneoudine-51
4               paris-portedechamperret-6
                      ...
4995                 colombes-menelotte-8
4996                     paris-dantzig-37
4997                        paris-bac-142
4998     fontenaysousbois-valdefontenay-2
4999                 paris-henrybrisson-5
Name: ID, Length: 5000, dtype: object

In [17]:
#Removing ©- the copyright sign from words in the address column
df['Address'] = df['Address'].str.replace("©","")
df['Address']

0                      2 Avenue de Suffren
1                145 Rue Raymond Losserand
2         2 Avenue John Fitzgerald Kennedy
3                    51 Rue EugÃ¨ne OudinÃ
4       6 avenue de la Porte de Champerret
                       ...
4995                    8 avenue MÃnelotte
4996                     37 rue de Dantzig
4997                        142 rue du Bac
4998           2 avenue du Val de Fontenay
4999                   5 Rue Henry Brisson
Name: Address, Length: 5000, dtype: object

Accuracy

In [18]:
#In-record and cross data set errors
df

                                 Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                  51 Rue EugÃ¨ne OudinÃ     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                  8 avenue MÃnelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 22 columns]

Completeness

In [21]:
#This involves checking for null values
df.isnull()

# Checking if there is any missing value across each column
df.isnull().any()


# Doing a quick check to see if we have any missing values at all

print(df.isnull().values.any())

#There are no missing values in the data set

False

Consistency

In [25]:
#Checking for duplicates in the dataset
print(df)
df_non_duplicates = df.drop_duplicates()
print(df_non_duplicates)

#There are no duplicates in the dataset

                                 Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                  51 Rue EugÃ¨ne OudinÃ     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                  8 avenue MÃnelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 22 columns]
                                 Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                  51 Rue EugÃ¨ne OudinÃ     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                  8 avenue MÃnelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 22 columns]

Uniformity

In [28]:
#Renaming column names according to the pascal case
df.columns=['Address' , 'Cars' , 'BlueCarCounter' ,'UtilibCounter' , 'Utilib1.4Counter' , 'ChargeSlots' , 'ChargingStatus' , 'City' , 'Id' , 'Kind' , 'PostalCode' , 'PublicName' , 'RentalStatus' , 'Slots' , 'StationType' , 'Status' , 'SubscriptionStatus' , 'Year' , 'Month' , 'Day' , 'Hour' , 'Minute']
df.columns.values.tolist()

['Address',
 'Cars',
 'BlueCarCounter',
 'UtilibCounter',
 'Utilib1.4Counter',
 'ChargeSlots',
 'ChargingStatus',
 'City',
 'Id',
 'Kind',
 'PostalCode',
 'PublicName',
 'RentalStatus',
 'Slots',
 'StationType',
 'Status',
 'SubscriptionStatus',
 'Year',
 'Month',
 'Day',
 'Hour',
 'Minute']

In [53]:
#Data type conversion
#Converting the month,day,year,time columns to date time and combining them
df['Date'] =pd.to_datetime(df[['Year', 'Month', 'Day', 'Hour', 'Minute']])
df
#Dropping the minute,hour,day,month, and year columns now that we have a cobmined column
df.drop(["Year" , "Month" ,"Day" , "Hour" , "Minute"], axis = 1, inplace = True)
df.head(10)

                              Address  ...                Date
0                 2 Avenue de Suffren  ... 2018-04-08 11:43:00
1           145 Rue Raymond Losserand  ... 2018-04-06 07:24:00
2    2 Avenue John Fitzgerald Kennedy  ... 2018-04-03 20:14:00
3               51 Rue EugÃ¨ne OudinÃ  ... 2018-04-04 04:37:00
4  6 avenue de la Porte de Champerret  ... 2018-04-08 17:23:00
5                8 Boulevard Voltaire  ... 2018-04-06 07:02:00
6                      37 rue Leblanc  ... 2018-04-08 18:20:00
7          17 Rue des Luaps ProlongÃe  ... 2018-04-04 22:13:00
8               34 avenue Jean Moulin  ... 2018-04-02 22:58:00
9        41 boulevard de Rochechouart  ... 2018-04-04 15:02:00

[10 rows x 18 columns]

Analysis

In [148]:
#Most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018.
#To compute usage, we will need to understand that we have to join successive (in time) measures/counters 
#for a given station, as the difference will tell whether a car was picked up, returned, or nothing happened.
#x=df['Date'].groupby(df['PublicName'])
#x.sum()
#most_populated=df.groupby(['PublicName']).sum().sort_values('Total' , ascending=0).head(5)
# 
y=df[(df['City']== 'Paris')]
grouped = y.groupby('PublicName')
grouped = y.groupby('Date', axis='columns')
grouped = y.groupby(['PublicName', 'Date' , 'BlueCarCounter'])
grouped['BlueCarCounter'].sum()

PublicName                Date                 BlueCarCounter
Paris/25 AoÃ»t 1944/8     2018-04-01 18:40:00  1                 1
                          2018-04-02 07:37:00  4                 4
                          2018-04-02 12:49:00  2                 2
                          2018-04-04 03:10:00  3                 3
                          2018-04-04 18:48:00  1                 1
                                                                ..
Paris/Ãtienne Marcel/36  2018-04-08 23:45:00  0                 0
                          2018-04-09 10:53:00  1                 1
                          2018-04-09 13:59:00  1                 1
Paris/Ãvangile/45        2018-04-03 09:50:00  6                 6
                          2018-04-09 04:57:00  4                 4
Name: BlueCarCounter, Length: 2816, dtype: int64

In [72]:
#Most popular station overall
df['PublicName'].value_counts()

Paris/Porte de Montrouge/8       13
Paris/Philippe Auguste/126       11
Paris/Voltaire/182               11
Paris/Courcelles/69              11
Paris/Mathis/35                  11
                                 ..
Paris/Pierre 1er de Serbie/33     1
Paris/Roubo/1                     1
Paris/Porte Pouchet/6             1
Paris/Pyramides/Parking           1
Meudon/Jeanne Braconnier/3        1
Name: PublicName, Length: 1105, dtype: int64

In [121]:
#What postal code is the most popular for picking up Blue cars? Does the most popular station belong to that postal code?
#df['BlueCarCounter'].groupby(df['PostalCode']).value_counts()
df['PostalCode'].value_counts()
#df['BlueCarCounter']
y=df.groupby(['PostalCode'])['BlueCarCounter'].count()
y.sort_values(ascending=False)
#Most popular code is 75015
df.loc[(df['PublicName'] == 'Paris/Porte de Montrouge/8') ,['PostalCode']].head(1)
#Most popular station does not belong to the most popular code

     PostalCode
122       75014

In [123]:
#Do the results change if you consider Utilib and Utilib 1.4 instead of Blue cars? 
y=df.groupby(['PostalCode'])['Utilib1.4Counter'].count()
y.sort_values(ascending=False)
#No result does not change
y=df.groupby(['PostalCode'])['UtilibCounter'].count()
y.sort_values(ascending=False)

PostalCode
75015    274
75016    236
75017    221
75011    180
75020    169
        ...
75116      5
91400      4
93310      4
92110      4
94100      2
Name: UtilibCounter, Length: 107, dtype: int64